In [1]:
import pandas as pd
import numpy as np

### country

In [30]:
country = countryNameAndCode[['Country']]
n = len(country)
country.ix[:, 'pred_rank'] = 0
country.ix[:, 'pred_gold'] = 0
country.ix[:, 'pred_silver'] = 0
country.ix[:, 'pred_bronze'] = 0
# pred_rank
# pred_gold
# pred_silver
# pred_bronze
country.to_csv('resources/data clean/country.csv')

### economics

In [48]:
def getData(gdp, cpi, income, population):
    countryCode = gdp.index
    yearCol = gdp.columns[1:]
    tempDict = {'code': [], 'year': [], 'gdp': [], 'population': [], 'income': [], 'cpi': []}
    for c in countryCode:
        for y in yearCol:
            tempDict['code'].append(c)
            tempDict['year'].append(y)
            tempDict['gdp'].append(gdp.ix[c, y])
            tempDict['cpi'].append(cpi.ix[c, y])
            tempDict['population'].append(population.ix[c, y])
            tempDict['income'].append(income.ix[c, y])
    tempDf = pd.DataFrame(tempDict)
    return tempDf
# code CHAR(3),
# year INTEGER,
# GDP FLOAT,
# population FLOAT,
# income FLOAT,
# CPI FLOAT,
economics = getData(countryGDP, countryCPI, countryrevenue, countrypopulation)
economics.to_csv('resources/data clean/economics.csv')
countryGDP.columns

### PerformanceOfCountries

In [3]:
countryOlympics = pd.read_csv('./resources/data clean/1896-2008 sports wise medal records.csv', header=0)

In [4]:
countryOlympicsTemp = countryOlympics[['Edition', 'NOC', 'Medal']]

In [5]:
countryOlympics = countryOlympicsTemp.pivot_table(index=['NOC', 'Edition'], values=['Num'], columns=['Medal'], aggfunc=np.sum)

In [6]:
def addRank(df): #countryOlympicsTemp
#     tempdf = df.groupby(['Edition', 'NOC'])['Num'].sum()
    tempdf = df.pivot_table(index=['NOC', 'Edition'], values=['Num'], columns=['Medal'], aggfunc=np.sum)
    tempdf = tempdf.fillna(0)
    tempdf.ix[:, 'Rank'] = 0
    year = df['Edition'].unique()
    for y in year:
        tempdfyear = df[df['Edition'] == y]
        tempdfcountry = tempdfyear.groupby('NOC')['Num'].sum()
        num = len(tempdfcountry)
        tempdfrank = num - tempdfcountry.argsort()
        for a in tempdfrank.index:
            tempdf.ix[(a, y), 'Rank'] = tempdfrank.ix[a]
    return tempdf

In [149]:
tempdf.to_csv('./resources/data clean/performanceofcountries.csv')

### PerformanceOfCountries 2012-2016

In [2]:
data = pd.read_csv('./resources/data clean/prediction.csv', header=0, index_col=0)

In [7]:
data2016 = data[['2012_CPI', '2012_r', '2016', '2016_s', '2016_b']]

In [9]:
data2016.ix[:, '2012_CPI'] = 2016

/home/chen/anaconda2/lib/python2.7/site-packages/pandas/core/indexing.py:465: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [10]:
data2016.columns = ['YEAR', 'RANK', 'RNAK','NUM_OF_GOLD', 'NUM_OF_SILVER', 'NUM_OF_BRONZE']

      2012_CPI  2016  2016_s  2016_b  2012_r
code
AFG       2016     0       0       0      79
ARG       2016     3       1       0      43
ARM       2016     1       3       0      61
AUS       2016     8      11      10       8
AUT       2016     0       0       1      86
AZE       2016     1       7      10      30
BEL       2016     2       2       2      61
BLR       2016     1       4       4      26
BRA       2016     7       6       6      22
CAN       2016     4       3      15      36
CHN       2016    26      18      26       2
COL       2016     3       2       3      38
CUB       2016     5       2       4      16
CZE       2016     1       2       7      19
DOM       2016     0       0       1      46
ESP       2016     7       4       6      21
EST       2016     0       0       1      63
ETH       2016     1       2       5      24
FIN       2016     0       0       1      58
FRA       2016    10      18      14       7
GBR       2016    27      23      17       3
GEO       2016     2       1       4      39
HUN       2016     8       3       4      10
IND       2016     0       1       1      55
IRL       2016     0       2       0      42
ISR       2016     0       0       2      86
ITA       2016     8      12       8       9
JAM       2016     6       3       2      18
JPN       2016    12       8      21      11
KAZ       2016     3       5       9      12
KEN       2016     6       6       1      28
LTU       2016     0       1       3      33
MAR       2016     0       0       1      79
MDA       2016     0       0       1      75
MEX       2016     0       3       2      39
NOR       2016     0       0       4      34
NZL       2016     4       9       5      15
POL       2016     2       3       6      30
ROU       2016     1       1       3      27
SRB       2016     2       4       2      43
SWE       2016     2       6       3      37
THA       2016     2       2       2      57
TJK       2016     1       0       0      79
TUN       2016     0       0       3      35
TUR       2016     1       3       4      41
UKR       2016     2       5       4      14
USA       2016    46      37      38       1
UZB       2016     4       2       7      48